### ISSUE TITLE
GoodKarma realword pieces information

### ISSUE THREAD

**Issue by carlosguadir** [florianwns/z5omes#41]
I would like to know if it's possible print detailed information for GoodKarma pieces. I would love the idea of print cut angles vertical and horizontal. [Acidome](https://acidome.com/lab/calc/#7/12_Kruschke_GoodKarma_3V_R2.20_beams_120x40) has it's section where is possible see the cut details for pieces.

**Comment by florianwns** [comment]
Hi Carlos,
of course, it's possible and it's already in todo list ;)
I hope it will be ready for Christmas 🎄

You can keep an eye on my todo.md file
or otherwise I post the new versions directly on Facebook: https://www.facebook.com/groups/Zomenetwork

Maybe I'll create a community blog later, if there are more requests.

Best regards.

**Comment by florianwns** [comment]
Hi @apalestrini and all buenos Aires !!!
Thx for your comment. 

I'm currently work on it. 
I hope push this feature in march.

**Comment by StephanMunduruku** [comment]
Salut Florian, je viens de voir une publication au sujet de Z5omes dans laquelle il y a une option "timber profile" précisant les angles nécessaires à un bon ajustement des losanges.
Je n'ai pas cette option tellement utile, faut-il que j'actualise quelque chose ? 
Bravo pour ce programme !

**Comment by florianwns** [comment]
Bonjour Stephane,
Cette option sera dispo vers fin mars/debut avril en ligne si J'ai le temps
de développer d'ici là.
À+

**Comment by StephanMunduruku** [comment]
Excuse, j'avais mal lu le post, ce n'est qu'après que j'ai compris que tu développais cette option.
________________________________
De : Florian REY ***@***.***>
Envoyé : dimanche 18 février 2024 15:10
À : florianwns/z5omes ***@***.***>
Cc : StephanMunduruku ***@***.***>; Comment ***@***.***>
Objet : Re: [florianwns/z5omes] GoodKarma realword pieces information (Issue #41)


Bonjour Stephane,
Cette option sera dispo vers fin mars/debut avril en ligne si J'ai le temps
de développer d'ici là.
À+

**Comment by apalestrini** [comment]
Chère @florianwns, si tu considères que je peux aider pour quelque chose, contribuer à cette nouvelle exigence, compte sur moi...
Du rôle de bêta-testeur à la fourniture de la documentation requise.
Pour l'instant je diffuse ton[ "buy me a coffee"](https://www.paypal.com/paypalme/z5omes)

**Comment by florianwns** [comment]
Merci Alejandro pour ta proposition.
Je suis en train de développer pas mal de nouvelles fonctionnalités donc les mesures des montants bois. Je mettrai la nouvelle version en ligne fin mars en principe. Tu pourras la tester à ce moment là. Mais pour la suite, j'essaierai de faire un mise en ligne de projets en cours de développment pour les futurs beta testeurs comme toi. A très vite

**Comment by apalestrini** [comment]
Excellent, je suis toujours attentif à votre projet.
Merci beaucoup...
Avec nos meilleures salutations.

**Comment by florianwns** [comment]
I close the issue....see v1.0.10 version of Z5omes
